### ISSUE TITLE
[1.1.0] Valves not updating

### ISSUE THREAD

**Issue by ChrisMisker** [arjenbos/ha_alpha_innotec#15]
When the valves are first added to HA, the right state (open/closed) are shown. However, after a while, the state of the valve change ofcourse. I can see this happening when I'm viewing the Gateway wireless components page. However, I don't not see this state change happening in Home Assistant. 
I also tried drastically changing the temperature in Home Assistant, so I'm sure the valves should open or close, but nothing happens to the state in Home Assistant. In real life, I can hear the valves opening or closing and I see this in the Gateway webpage as well, just not in Home Assistant.
I waited about 5 minutes and now it's about 10 minutes, and I still don't see it in Home Assistant.

**Comment by arjenbos** [comment]
I already thought so. This is also the case for the battery sensor.
