### ISSUE TITLE
Set up a heat pump

### ISSUE THREAD

**Issue by SchBenedikt** [arjenbos/ha_alpha_innotec#28]
Let’s assume I have an Alpha Innotec heat pump. Then there are various configuration options such as: B. Gateway IP address, password, etc. What do you have to write in there so that everything is configured correctly?
What do you mean by gateway exactly? The Internet connection?
Unfortunately there is no proper description for this...
But as soon as I know, I might add these too.

Best regards,
schBenedikt

**Comment by ChrisMisker** [comment]
Hi @SchBenedikt , this is for the Alpha Home system, which is a system with thermostats and valves to control floor heating and radiators and such. 
If you have an Alpha Innotec heat pump, you should use this integration to interact with: https://github.com/BenPru/luxtronik

@arjenbos Perhaps it's better to rename this integration to Alpha Home, because I can understand it's confusing.

**Comment by DrBlokmeister** [comment]
I agree. Maybe we should change this issue to a feature request for more documentation/guidance on setting this up.

**Comment by arjenbos** [comment]
Ah, like mentioned in the README I do not own an Alpha Innotec/Home system. I thought they were the same. When I have the time, then I will rewrite everything from Innotec to Home.

**Comment by SchBenedikt** [comment]
> Hi @SchBenedikt , this is for the Alpha Home system, which is a system with thermostats and valves to control floor heating and radiators and such. If you have an Alpha Innotec heat pump, you should use this integration to interact with: https://github.com/BenPru/luxtronik
> 
> @arjenbos Perhaps it's better to rename this integration to Alpha Home, because I can understand it's confusing.

Yes, but that what you said is outdated... That would be better for it, right?
https://github.com/Bouni/luxtronik

**Comment by ChrisMisker** [comment]
No, the BenPru is the newer and better version (but do make sure you get the latest beta, it’ll work fine!). The Bouni version will have you add the sensors yourself, while the BenPru version already has a bunch of sensors (a huge bunch!) ready for you, so much easier. And quicker to updates as well. So go for the BenPru version.

**Comment by SchBenedikt** [comment]
@ChrisMisker Thanks!
Thanks, do you know whether port 8889 is always the right port or where you can check it?
And what do the other fields mean? - The translation doesn't work...
<img width="308" alt="image" src="https://github.com/arjenbos/ha_alpha_innotec/assets/137323528/f39c50bf-fedf-4abc-b18d-ee6f37046e94">

**Comment by ChrisMisker** [comment]
Make sure you also post that screenshot and the missing translation at the BenPru repository. They are actively hunting bugs!

but, yes, probably you can leave all the settings as default. Just change the first textbox (where it now says wp-novelan) to the IP of the heat pump. 
I think it’s 60 seconds for time out. And 10.000 is the buffer size. But no need to change those.

**Comment by SchBenedikt** [comment]
@ChrisMisker Thanks for your help!
Do you happen to know - if you have such a heat pump - whether a graphical interface also appears under the IP-address:8889?

**Comment by ChrisMisker** [comment]
If you go to the IP (no port necessary), and enter password 999999, you're in the web ui. If the web ui isn't showing, your heatpump isn't properly connected to the network (or doesn't have a networking interface).
