### ISSUE TITLE
Component won't connect to Alpha Home

### ISSUE THREAD

**Issue by meameameamea** [arjenbos/ha_alpha_innotec#30]
Hello,

I have a Alpha Innotec heatpomp with the Luxtronix custom component installed. 
I have it combined with an Alpha Home system with several thermostats and floor heating groups. 
When trying to connect it won't and shown error "Unknown error occurred"

If i try to connect with the wrong password (controlbox) it shows "cannot_connect"
Home Assistant 2024.01.01
controlbox and gateway v 2.2.39533

How can i generate debug information to help you debug?

**Comment by arjenbos** [comment]
Hi @meameameamea ,

Is it possible for you to share some debug logs? See https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics.

Please check the output before you submit the info in this issue, it may contain sensitive information.

**Comment by DrBlokmeister** [comment]
Another question: have you had it working before or is this an error that you get during setup? 

If it's a setup issue, I usually make the stupid mistakes such as wrong IP addresses (both heatpump and controller), wrong passwords, etc.

If you had it working before, did you recently change anything? Did it for example suddenly stop working when you updated this integration or when you updated Home Assistant?

**Comment by meameameamea** [comment]
Ok, found what it was. 
I got error, "Unable to fetch data from API: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))". 
But i created a user account for home assistant. I should have created and account  with admin/manager right on the controlbox. So trying to login with account with user priviledge leads to close connection from the controller end. 

P.S. perhaps a good idea to mention this in the readme
