### ISSUE TITLE
Unable to set up integration with WZSV 92K3M Heat pump 

### ISSUE THREAD

**Issue by mindej** [arjenbos/ha_alpha_innotec#32]
I have https://www.alpha-innotec.com/en/products/ground-source-heat-pumps/wzsv-series heat mump installed in my home but I am not able to set up Integration.

Local network is working fine but I am able to login to it over WEB interface.

**Comment by ChrisMisker** [comment]
You should use the benpru/luxtronik2 integration. This one is for the Alpha Home system.
