### ISSUE TITLE
Feature request: show status of underfloor heating distributor groups

### ISSUE THREAD

**Issue by ChrisMisker** [arjenbos/ha_alpha_innotec#4]
This is really a great custom component. Really great work!

It would be awesome if the component could also show the underfloor heating distributors and the status (open or closed) of its groups.

**Comment by arjenbos** [comment]
Hi @ChrisMisker ,

Do you have more information from your installation? Like which API endpoint returns this information? And what are the request parameters for this endpoint?

Thanks!

**Comment by arnebret** [comment]
I can chip in here. It's in the /api/gateway/dbmodules endpoint. Here's an example:

        "00050E9BA06530A": {
            "id": 9,
            "deviceid": "00050E9BA06530A",
            "nodeid": "10",
            "name": "Regelmodule Vloerverwarming",
            "room": "",
            "currentTemperature": "off",
            "battery": "off",
            "binarySwitch": false,
            "isFailed": false,
            "lastResponse": 1698431877000,
            "interviewDone": true,
            "vendorId": 380,
            "productId": 3,
            "type": "floor",
            "instances": [
                {
                    "instance": "1",
                    "room": 0,
                    "status": false
                },
                {
                    "instance": "2",
                    "room": 0,
                    "status": false
                },
                {
                    "instance": "3",
                    "room": 0,
                    "status": false
                },
                {
                    "instance": "4",
                    "room": 0,
                    "status": false
                },
                {
                    "instance": "5",
                    "room": 0,
                    "status": false
                },
                {
                    "instance": "6",
                    "room": 0,
                    "status": false
                },
                {
                    "instance": "7",
                    "room": 0,
                    "status": true
                },
                {
                    "instance": "8",
                    "room": 0,
                    "status": false
                }
            ]
        }


DeviceID and name won't help you as these will vary per installation. However the 'productID': 3 will let you know that it's a UFH distributor. Every instance is a single valve, so probably just create a simple binary sensor for each of them with the status as an attribute.

Nice to have: several valves are often combined per room. So for example instance 1 to 4 are for the living room and are controlled as one zone. You can't get that info from this endpoint, but it's somewhere in the system, so maybe available via an endpoint. Don't spend to much time on this however, as you can just group the sensors in HA quite easily.

**Comment by arjenbos** [comment]
That's some very useful information @arnebret ! I will have a look.

**Comment by arnebret** [comment]
Great stuff @arjenbos! Did a quick test of the main branch and it seems to work exactly as it should, perfect!

**Comment by arjenbos** [comment]
Nice! Thanks for testing @arnebret :smile:
